name: Generate & publish content

on:
  schedule:
    # Twice a week at 14:00 UTC (adjust as you like)
    - cron: "0 14 * * 1,4"
  workflow_dispatch: {}  # allow manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}       # e.g., yourtag-20
          AMAZON_TLD: "com"                           # change if needed
          KEYWORDS_FILE: "keywords.txt"
          AFFILIATE_PRODUCTS: "affiliate_products.csv"
          OPENAI_MODEL: "gpt-4o-mini"
        run: |
          python scripts/auto_generate.py --limit 2
